### PR TITLE
Use "height_percentile" as "height" column

### PR DESCRIPTION
**Pull request by jcass11**
This PR sets the `height` column to use the `height_percentile` feature. The old `height` column uses the difference in z between the highest and lowest points in the segmentation whereas the new `height_percentile` feature uses the 1st and 99th percentile z values, which helps to eliminate erroneous outlier pixels.  The validation with watershed images is much better with the new feature that handles outlier pixels better. The values are similar (see scatter plot of height vs height_percentile), and the colony time alignment is identical for the small-medium lag and shifts by 2 frames for the medium-large lag when we make this change.

height_vs_height_percentile
[avg_height_colony_colony_time_alignment_percentile.pdf](https://github.com/user-attachments/files/17033828/avg_height_colony_colony_time_alignment_percentile.pdf)

### CODE REVIEW

**Comment by jcass11** [comment]
I'm having a funny issue where without changing anything about @ritvikvasan ’s shell scripts git forces me to "commit my changes" to them. Then on my PR is shows them as changed files but they're actually identical. Sounds like @cfrick13 is having the same issue.

**Review by chantelleleveille — APPROVED** [review]
I approve the height changes. Can merge once we get the .sh files sorted out!

**Comment by cfrick13** [comment]
I also approve. Looks like it should catch all dataframe loads. Hopefully the .sh file issue is quick to fix.

**Review by cfrick13 — APPROVED** [review]

**Comment by chantelleleveille** [comment]
I reverted the .sh files back to executable (100755) on this branch using the tip from @mogres to edit `./.git/config` filemode = false so that git would not track that our file system had changed its permissions.

**Pull request merged**
