### PR TITLE
load all_baseline before subsetting

### PR DESCRIPTION
**Pull request by chantelleleveille**
Our load dataset functions do not currently support loading subset colony datasets using the keys: `"small", "medium", "large"`. Updated figure 1 workflows to load "all_baseline" before subsetting to a particular colony. This update makes sure `figure1_dataset` succeeds when running `run_all_manuscript_workflows.py`.

```
====== Successes ======
figure1_dataset (1927.0s) (48.0GB)
====== 1 succeeded  ======
```

A future PR could update the load dataset functions to work with the colony keys.

### CODE REVIEW

**Comment by jcass11** [comment]
Thanks for addressing this ongoing error we've had! Testing by running `pdm run run_all_manuscript_workflows.py --only figure1_dataset` now

**Comment by jcass11** [comment]
> Thanks for addressing this ongoing error we've had! Testing by running `pdm run run_all_manuscript_workflows.py --only figure1_dataset` now

Workflow succeeded and figures look good!
```
====== Successes ======
figure1_dataset (1674.9s) (50.4GB)
====== 1 succeeded  ======
```

**Review by jcass11 — APPROVED** [review]
Thank you!

**Review by pgarrison — APPROVED** [review]
> A future PR could update the load dataset functions to work with the colony keys.

I'd love to see it but I also love that we are making small PRs like this to address one thing at a time!

**Pull request merged**
