### PR TITLE
Add density calc to perturbation main manifest

### PR DESCRIPTION
**Pull request by chantelleleveille**
@cfrick13  I tried added the code as it was in `generate_main_manifest` to the perturbation one but am running into issues. It was taking days to run and printing errors that look like this:

```
in generate_manifest_one_colony density_df = 
watershed_workflow.get_pseudo_cell_boundaries_for_movie(dataset, parallel=True) 
File "../nuc-morph-analysis/nuc_morph_analysis/lib/preprocessing/twoD_zMIP_area/watershed_workflow.py", 
line 89, in get_pseudo_cell_boundaries_for_movie p.terminate() 
UnboundLocalError: local variable 'p' referenced before assignment
```

I wanted to take this off your plate but we might need to troubleshoot together!

### CODE REVIEW

**Comment by cfrick13** [comment]
# updates:
1. changed `generate_perturbation_manifest.py` to run within `if __name__ == "__main__":` and it worked! 
     - `pdm run python nuc_morph_analysis/lib/preprocessing/generate_perturbation_manifest.py` ran successfully.
2. uploaded new `2024-12-05_drug_perturbation_main_manifest.parquet` and `2024-12-05_feeding_control_main_manifest.parquet` to FMS
3. updated FMS ids in `all_datasets.py`. 

# tests:
1. `pdm run python run_all_manuscript_workflows.py --only figure_s12_feeding_control figure_s6_s16_inhibitors` ran successfully!
====== Successes ======
figure_s12_feeding_control (619.6s) (27.1GB)
figure_s6_s16_inhibitors (613.7s) (14.9GB)
====== 2 succeeded  ======

**example outputs**
image
image

2. I confirmed that density values make sense for drug_perturbation and feeding_control colonies (code is: `/analyses/density/extra_checks/check_that_density_works_for_perturbations.py`
image
image
image

**Review by cfrick13 — APPROVED** [review]

**Review by jcass11 — APPROVED** [review]
Great! Thank you!

**Comment by cfrick13** [comment]
Final update
```
====== Successes ======
figure_1_dataset (455.7s) (47.9GB)
figure_3_s4_height_density (731.9s) (48.9GB)
figure_4_s8_volume_trajectories (76.1s) (26.5GB)
figure_5_s9_s10_local_growth (267.4s) (45.0GB)
figure_6_s11_compensation (97.8s) (26.5GB)
figure_7_s13_s14_lineage (295.8s) (26.5GB)
figure_s12_feeding_control (150.4s) (22.9GB)
figure_s15_linear_regression_model (1477.5s) (26.9GB)
figure_s19_transition_point (19.5s) (26.4GB)
figure_s1_cell_health (15.5s) (23.3GB)
figure_s20_precision_error (9.2s) (5.3GB)
figure_s2_s3_s18_segmentation_model_validation (162.2s) (8.6GB)
figure_s6_s16_inhibitors (200.6s) (16.5GB)
figure_s7_growth_outliers (86.7s) (27.7GB)
====== 14 succeeded  ======
```

**Comment by jcass11** [comment]
YESSSS! Nice work!

**Pull request merged**
