### PR TITLE
Fix height -> height percentile in two additional places

### PR DESCRIPTION
**Pull request by jcass11**
I previously merged a PR
- #24 

that added a step to our data loading to swap the `height_percentile` values into the `height` column to easily make all workflows using `height` to use the same `height_percentile` values. 

In regenerating all of the figures that need to be swapped out as a result of this change, I found that some workflows were not caught by these changes:
- `quantitative_validation_workflow` which loads its data from a url in a separate way from how our baseline colony analyses do
- `fixed_control_analysis_manuscript_workflow` which led me to realize that a bunch of workflows have their own load functions that don't tie in to where I updated height. However they all commonly load from `get_dataframe_by_info` so I updated that function to hopefully fix all of those workflows.

Additional edit: `pdm sync` with `pdm.lock` and `pyproject.toml` wasn't actually giving me colorizer v 1.4.2 to I had to update them here. This is related to height because I needed to regenerate TFE input data using `height_percentile` to update paper figures that are generated via TFE.

Testing: I reran the above two workflows and confirmed that they run without error and result in figures that use `height_percentile` values rather than the old `height` values.

Sorry I missed these in my first pass - I think we should be all set now...

### CODE REVIEW

**Review by mogres — APPROVED** [review]

**Comment by jcass11** [comment]
I'm confused - I merged `dev` into my branch to make sure it was up to date. There were some `colorizer` updates that were needed to `pdm.lock` and `pyproject.toml` but all other edits to `pdm.lock` weren't made by me. But yet it says they're all changes relative to `dev` even though they were made as a result of merging `dev` in... I'm very confused. Would @pgarrison know anything about why that's happening?

**Review by pgarrison — APPROVED** [review]
Changes to the dependencies look good to me!

**Comment by chantelleleveille** [comment]
This would be a separate PR but while you are working on this would you mind pulling the bioRxiv-v1 branch and updating the project.toml file for colorizer v1.4.2 and making sure we get this right there as well? I think my mistake spans both main branches.

**Comment by jcass11** [comment]
> This would be a separate PR but while you are working on this would you mind pulling the bioRxiv-v1 branch and updating the project.toml file for colorizer v1.4.2 and making sure we get this right there as well? I think my mistake spans both main branches.

Sure thing!

**Comment by jcass11** [comment]
> This would be a separate PR but while you are working on this would you mind pulling the bioRxiv-v1 branch and updating the project.toml file for colorizer v1.4.2 and making sure we get this right there as well? I think my mistake spans both main branches.

This is now in an open PR #31

**Pull request merged**
